version: "3.8"
services:
  db:
    image: postgres:14
    container_name: cocktail_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iLoveGyubee
      POSTGRES_DB: cocktail_api_project
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: cocktail_api_web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:iLoveGyubee@db:5432/cocktail_api_project

volumes:
  pgdata:
