name: Build and Test Docker App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      - name: Run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for DB to be ready
        run: sleep 15

      - name: Run custom DB check
        run: |
          docker ps
          docker exec cocktail_api_web node index.js

      - name: Tear down
        run: docker-compose down
